# Site settings
name: NoVAD
title: "Better Cloud Safeguards"
description: "The cloud needs better safeguards to prevent disasters, when criminals and terrorists strike or ordinary mistakes happen"
baseurl: ""
url: "http://www.novad.club"
linked_in_url: "http://n99.us/nli"
exclude: ['README.md']
tweet_text: "The Cloud Needs Airbags, better safeguards for your data"

# Github defaults
safe: true
highlighter: pygments
lsi: false
defaults:
  - 
    scope:
      path: "en"
    values:
      layout: "page"

# Build settings
permalink: none
markdown: kramdown
kramdown:
  auto_ids: false
